---
# handlers file for rsyslog

- name: restart rsyslog
  ansible.builtin.service:
    name: "{{ rsyslog_service }}"
    state: restarted
  when:
    - not ansible_check_mode | bool

- name: systemd daemon reload
  ansible.builtin.systemd:
    daemon_reload: true

...
